# Permission for an authorized player
authorized-permission: "permission"

# The message that is displayed for an unauthorized user
unauthorized-message:
  normal: "your text 1"
  nether: "your text 2"
  end: "your text 3"