# Permission for an authorized player
authorized-permission: "permission"

# The message that is displayed for an unauthorized user
unauthorized-message:
  normal: "your text 1"
  nether: "your text 2"
  end: "your text 3"

# afk time in minutes
afk-time: 1

spawn-protection:
  spawn-radius: 0
  advancement-count-limit: 0

  # Accepts the '{advLastCount}' parameter
  action-bar-message: "message"

  attempt-count: 0
  chat-message:
    - "message 1"